name: CI
on:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.3 ruff
      - name: Ruff
        run: |
          ruff --version
          ruff .
      - name: Run execute.py
        run: |
          python execute.py > result.json
      - name: Copy to public for Pages
        run: |
          mkdir -p public
          cp result.json public/
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
